version: '2'
services:
  postgres:
    image: "postgres:9.6.3"
    hostname: "postgres"
    environment:
      POSTGRES_USER: "sa"
      POSTGRES_PASSWORD: "Qwe1234!"
      POSTGRES_DB: "prometheus"
    ports:
      - "5432:5432"
  redis:
    image: "redis:3.0.7"
    hostname: "redis"
    ports:
      - "6379:6379"
  rabbit:
    image: "rabbitmq:3.6.10-management"
    hostname: "rabbit"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
  elk:
    image: "sebp/elk:540"
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
